name: API Tests CI

on:
  push:
    branches: [ "main", "develop", "master" ]
  pull_request:
    branches: [ "main", "develop", "master" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Создаем .env для docker-compose из секретов
      - name: Create .env file for service
        working-directory: ./simbirsoft_sdet_project
        run: |
          # Используйте здесь те же имена, что и в ваших GitHub Secrets
          echo "HTTP_PORT=${{ secrets.HTTP_PORT }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_HOST=postgres" >> .env # Важно для связи контейнеров

      - name: Start API Service and DB
        working-directory: ./simbirsoft_sdet_project
        run: docker compose up --build -d

      - name: Wait for service to be healthy
        run: |
          echo "Waiting for service to be ready..."
          # Пытаемся подключиться к порту в течение 60 секунд
          timeout 60s bash -c 'until nc -z $0 $1; do sleep 5; done' localhost ${{ secrets.HTTP_PORT }}

      - name: Run Pytest
        env:
          BASE_URL: http://localhost:${{ secrets.HTTP_PORT }}
        run: pytest -n auto --alluredir=allure-results --clean-alluredir

      # Собираем логи Docker, если тесты упали
      - name: Get Docker logs on failure
        if: failure()
        working-directory: ./simbirsoft_sdet_project
        run: docker compose logs

      - name: Tear down services
        if: always()
        working-directory: ./simbirsoft_sdet_project
        run: docker compose down

      - name: Generate Allure Report
        if: success() || failure()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report