name: API Tests CI

# Триггеры: когда запускать этот процесс
on:
  # Запускать при каждом push в основную ветку
  push:
    branches: [ "main", "master" ]
  # Запускать при создании Pull Request в основную ветку
  pull_request:
    branches: [ "main", "master" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API Service
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run Pytest
        run: pytest -n auto --alluredir=allure-results

      # Шаг (только если тесты упали): Собираем логи Docker для отладки
      - name: Get Docker logs on failure
        if: failure()
        run: docker-compose logs

      - name: Set up Allure
        uses: allure-framework/setup-allure@v1
        with:
          version: 2.15.0

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report